added node pool attribute "temporary_name_for_rotation" to allow resizing k8s vms with only one node pool
dodevops/terraform-azure-kubernetes pull request #13
Opened 2024-04-09 07:08 UTC by salami738

added node pool attribute "temporary_name_for_rotation" to allow resizing k8s vms with only one node pool

2024-04-09 07:11 UTC, dploeger requested changes
Great, thanks! 🎁 

Could you please rename the commit so it confirms with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)?

2024-04-09 07:18 UTC, salami738 commented
Sorry. I don't make pull requests often enough. Commit Message Is fixed.

2024-04-09 07:41 UTC, salami738 commented
I added an additional fix after feedback from terraform testing.

2024-04-09 08:20 UTC, timdeluxe approved these changes
@dploeger Shall he rebase/squash before we merge?

2024-04-09 08:26 UTC, dploeger commented
@timdeluxe I'd go with rebase.

2024-04-09 12:00 UTC, salami738 commented
Found another useful feature and implemented it: Azure kubernetes node pool auto scaling.

2024-04-09 12:15 UTC, dploeger requested changes
Oh, just noticed: You didn't run the command

```
docker run -v "$PWD":/terraform ghcr.io/dodevops/terraform-module-tools:latest
``` 

Please do so and commit the README as well.

2024-04-10 09:19 UTC, salami738 commented
done.

2024-04-10 09:22 UTC, dploeger approved these changes
Great! Thanks. 🎁

2024-04-11 16:09 UTC, timdeluxe approved these changes

2024-04-12 06:30 UTC, merged

2024-04-12 06:30 UTC, dploeger commented
Released as 3.5.0